### ISSUE TITLE
[BUG] Cannot add custom voices

### ISSUE THREAD

**Issue by wookash** [linuxserver/docker-piper#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm adding new voice onnx and relevant onnx.json files to the config folder, I'm updating voices.json, the voice can be chosen in home assistant but there is error (see below)

### Expected Behavior

I'd like to be able to add custom voice

### Steps To Reproduce

copy voice files to config directory
update voices.json file
reload wyoming integration in home assistant
choose new voice in assistant
click play to try the new voice
error occurs

### Environment

```markdown
- OS: debian 12
- How docker service was installed: portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=xx
      - PGID=xx
      - TZ=xxx/xxx
      - PIPER_VOICE=en_US-lessac-high
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    volumes:
      - /xxxx:/config
    ports:
      - 10200:10200
    restart: unless-stopped
```

### Container logs

```bash
ERROR:asyncio:Task exception was never retrieved

future: <Task finished name='Task-9' coro=<AsyncEventHandler.run() done, defined at /lsiopy/lib/python3.12/site-packages/wyoming/server.py:28> exception=VoiceNotFoundError('jarvis')>

Traceback (most recent call last):

  File "/lsiopy/lib/python3.12/site-packages/wyoming/server.py", line 35, in run

    if not (await self.handle_event(event)):

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lsiopy/lib/python3.12/site-packages/wyoming_piper/handler.py", line 73, in handle_event

    piper_proc = await self.process_manager.get_process(voice_name=voice_name)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lsiopy/lib/python3.12/site-packages/wyoming_piper/process.py", line 114, in get_process

    ensure_voice_exists(

  File "/lsiopy/lib/python3.12/site-packages/wyoming_piper/download.py", line 77, in ensure_voice_exists

    find_voice(name, data_dirs)

  File "/lsiopy/lib/python3.12/site-packages/wyoming_piper/download.py", line 183, in find_voice

    raise VoiceNotFoundError(name)

wyoming_piper.download.VoiceNotFoundError: jarvis
```

**Comment by rodrigosiviero** [comment]
same here, @wookash  have you been able to solve it?

**Comment by wookash** [comment]
> same here, @wookash have you been able to solve it?

Nope, I gave up for now - running other projects..

**Comment by NeoJoris** [comment]
Any updates? @wookash @rodrigosiviero

**Comment by rodrigosiviero** [comment]
> Any updates? [@wookash](https://github.com/wookash) [@rodrigosiviero](https://github.com/rodrigosiviero)
> 
> I would like to add Jarvis voices from https://huggingface.co/jgkawell/ (atleast be able to try custom voice (links))

Yes, I've been able to use my custom onnx voice but not with this image, with HA addon itself like this:


```
  piper:  
      image: homeassistant/amd64-addon-piper:latest  
      container_name: piper
      entrypoint: python3  
      command: >  
        -m wyoming_piper  
        --piper '/usr/share/piper/piper'  
        --uri 'tcp://0.0.0.0:10200'  
        --length-scale "2"  
        --noise-scale "0.667"  
        --speaker "0"  
        --voice "en_GB-jarvis-high" 
        --max-piper-procs "1"  
        --data-dir /data  
        --data-dir /share/piper  
        --download-dir /data  
      ports:  
        - "10200:10200"  
      volumes:  
        - /piper/data:/data  
      restart: unless-stopped
```

1. Mount /data on the container to the host
2. Open the file named voices.json
3. Add the block of code for your specific onnx and onnx.json
4. generate the MD5SUM from the files and size in bytes
5. Upload the files at /data directory(root itself, no need to use folders just copy everything there)
6. restart piper/ha just to be sure and select on HA


here's the block for jarvis, I already did it for you

```
    "en_GB-jarvis-high": {
        "key": "en_GB-jarvis-high",
        "name": "Jarvis",
        "language": {
            "code": "en_GB",
            "family": "en",
            "region": "GB",
            "name_native": "English",
            "name_english": "English",
            "country_english": "Great Britain"
        },
        "quality": "high",
        "num_speakers": 1,
        "speaker_id_map": {},
        "files": {
            "en/en_GB/jarvis/high/en_GB-jarvis-high.onnx": {
                "size_bytes": 114199011,
                "md5_digest": "2921a440ebf4064ec761a5a02f66c65a"
            },
            "en/en_GB/jarvis/high/en_GB-jarvis-high.onnx.json": {
                "size_bytes": 7262,
                "md5_digest": "fecff68ce6f9b52ffaae52f06d824b05"
            },
            "en/en_GB/jarvis/high/MODEL_CARD": {
                "size_bytes": 309,
                "md5_digest": "b116c3cbdebac99ade9af03807cb9301"
            }
        },
        "aliases": [
            "en-gb-jarvis-low"
        ]
    },
```

note, I dont think the MODEL_CARD matters, I just left it there the original one that container downloads, or you can download the jarvis one and md5sum it as well.

Damn I wish I had the Jarvis voice in PT_BR

**Comment by Ocramius** [comment]
FWIW, what stands mostly in the way seems to be `--update-voices`:

https://github.com/linuxserver/docker-piper/blob/39dd7df7398c08f5da00ac17815eadf3bec64dce/root/etc/s6-overlay/s6-rc.d/svc-piper/run#L16

**Comment by Ocramius** [comment]
I no longer have full context of what I was doing, but `--update-voices` at start-up does some destructive operations on the environment (besides requiring network for something that should be baked in the image, but the python community has left operational sanity behind many years ago 😱).

In my case, I ended up dropping the custom container entirely, mounting my own models in the upstream container shipped as a Home Assistant plugin.

The startup of the entire container is madness even in that image though: I used an approach that works for me, ad stopped messing with it as much as possible.

**Comment by neoKushan** [comment]
> Hey, sorry to necro an old thread.
> 
> This is a somewhat easy fix... And I though I'd share how!
> 
> Add this to your docker-compose.yml file to load a custom script:
> 
> ```
>     volumes:
>       - ./piper:/config
>       - ./piper_scripts:/custom-cont-init.d:ro
> ```
> 
> Then within the ./piper_scripts dir create a file called setup.sh, ensure it's set to executable `chmod +x ./piper_scripts/setup.sh`
> 
> Then put this within the file: `sed -i 's|--download-dir /config --update-voices|--download-dir /config|' /run/service/svc-piper/run`
> 
> This will remove the --update-voices bit, which automatically updates the ./config/voices.json file. Which is a problem as now we want to edit that file to add a custom voice.
> 
> Next I download the GLaDOS voice from here -https://github.com/dnhkng/GLaDOS/tree/99fbf5e182ed2c60e075bd1241d67f68f6833b8e/models and place the files into the ./piper directory, then rename the .onnx and json file to
> 
> en_US-glados-medium.onnx and en_US-glados-medium.onnx.json
> 
> next edit the ./piper/voices.json and add the following:
> 
> ```
>     "en_US-glados-medium": {
>         "key": "en_US-glados-medium",
>         "name": "GLaDOS",
>         "language": {
>             "code": "en_US",
>             "family": "en",
>             "region": "US",
>             "name_native": "English",
>             "name_english": "English",
>             "country_english": "United States"
>         },
>         "quality": "medium",
>         "num_speakers": 1,
>         "speaker_id_map": {},
>         "files": {
>             "en/en_US/glados/medium/en_US-glados-medium.onnx": {
>                 "size_bytes": 63511038,
>                 "md5_digest": "a06f8b65ee1e4bf2dfcb0a80b560deeb"
>             },
>             "en/en_US/glados/medium/en_US-glados-medium.onnx.json": {
>                 "size_bytes": 7103,
>                 "md5_digest": "3c64107283b6077db37a9c9e1f8b7dcc"
>             }
>         },
>         "aliases": [
>             "en-us-glados-medium"
>         ]
>     },
> ```
> 
> Log into home assistant and reload the piper addin and it should show the GLaDOS voice as an option now.

Thank you *so much* for these steps - I finally got this working thanks to these steps. It seems adding custom models to piper - be it as a docker container standalone or even the Home Assistant addon - is an absolute nightmare with a bunch of poor decisions and ever-so-slightly incorrect documentation scattered around to make it difficult to get right. If you want GPU support it's even worse. 

So thank you again for the clear instructions.

**Comment by thespad** [comment]
Including all basic voices in the image would require it to be over 10Gb, which is *wildly* impractical for so many reasons. Including no voices and disabling the update mechanism across the board means everyone has to go through a ton of effort to get a basically functioning image. Including a subset of voices is predjudicial and will immediately get everyone yelling at us for not including the ones they wanted.

As an aside, you can already run the image with a read-only container filesystem, it's right there in the readme, which I'm sure has been read.

I'll add an option to disable the voice update on startup, now that it looks like the upstream project is actually under active development again.

**Comment by neoKushan** [comment]
> I'll add an option to disable the voice update on startup, now that it looks like the upstream project is actually under active development again.

Thank you, while I think the upstream project could do more to make custom models a bit easier to add, I think this will go a long way to simplifying things and feel a lot less hacky.
